### ISSUE TITLE
Newer version not working

### ISSUE THREAD

**Issue by UIOUY** [sniklaus/youtube-watchmarker#35]
I had the newest version installed, but it wasn't doing anything. Nothing was watched, clicking on it didn't bring up the synchronize tab. Tried turning it off and one, removing and readding it. Nothing worked

Using latest version of regular Firefox. Swapped back to Version 3.0.2 and it's working, though had to resync everything.

**Comment by sniklaus** [comment]
Thank you for reaching out and my apologies for the trouble! Just some questions to debug this: are you using the old or the new Youtube theme? If you click on the blue symbol to open the configuration page of the Youtube Watchmarker, there was nothing happening with the new version?

**Comment by UIOUY** [comment]
New Youtube as far as I can tell. Yes, nothing happened at all when clicking the icon. Right clicking just gave the usual manage extension options.

**Comment by sniklaus** [comment]
Could you do the following to see whether there are any error messages? Thanks!

- Install the newest version of the addon again.
- Navigate to `about:debugging` and then "This Firefox" on the left.
- Look for "Youtube Watchmarker" in the list and click on "Inspect".
- A new tab should be opening, go to the "Console" menu at the top.
- Copy and paste the messages from there.

**Comment by sniklaus** [comment]
Closing due to inactivity, please let me know in case you ever get to looking into this further. Thanks!

**Comment by OlegYch** [comment]
doesn't work for me either anymore
here is the debug log
```
initialized commons succesfully  background.js:1424:3
synchronized history  background.js:1399:7
mark video  background.js:1340:6
synchronized history  background.js:1399:7
Unchecked lastError value: Error: Missing host permission for the tab  ExtensionCommon.jsm:304
	withLastError resource://gre/modules/ExtensionCommon.jsm:304:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:357:11
Error: Could not establish connection. Receiving end does not exist.  undefined
synchronized history  background.js:1399:7
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
	objVideos/objAjax.onload moz-extension://f5735726-c930-4d9a-be72-efceb8fe8c3a/background.js:648:31
Unchecked lastError value: Error: Frame not found, or missing host permission  ExtensionCommon.jsm:304
Error: Could not establish connection. Receiving end does not exist.  undefined
Error: Missing host permission for the tab  undefined
Unchecked lastError value: Error: Missing host permission for the tab  ExtensionCommon.jsm:304
synchronized history  background.js:1399:7
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
Error: Could not establish connection. Receiving end does not exist.  undefined
Unchecked lastError value: Error: Missing host permission for the tab  ExtensionCommon.jsm:304
Unchecked lastError value: Error: Frame not found, or missing host permission  ExtensionCommon.jsm:304
synchronized history  background.js:1399:7
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
Error: An unexpected error occurred  undefined
Error: Could not establish connection. Receiving end does not exist.  undefined
Unchecked lastError value: Error: document.location is null  ExtensionCommon.jsm:304
Unchecked lastError value: Error: An unexpected error occurred  ExtensionCommon.jsm:304
Error: Could not establish connection. Receiving end does not exist.  undefined
Unchecked lastError value: Error: Frame not found, or missing host permission  ExtensionCommon.jsm:304
Error: Could not establish connection. Receiving end does not exist.  undefined
synchronized history  background.js:1399:7
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
synchronized history  background.js:1399:7
Error: Could not establish connection. Receiving end does not exist.  undefined
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
Error: Could not establish connection. Receiving end does not exist.  undefined
Error: An unexpected error occurred  undefined
Error: Could not establish connection. Receiving end does not exist.  undefined
Error: An unexpected error occurred  undefined
Error: Could not establish connection. Receiving end does not exist.  undefined
Error: An unexpected error occurred  undefined
Error: Could not establish connection. Receiving end does not exist.  undefined
synchronized history  background.js:1399:7
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
Error: Could not establish connection. Receiving end does not exist.  undefined
Error: An unexpected error occurred  undefined
Unchecked lastError value: Error: Frame not found, or missing host permission  ExtensionCommon.jsm:304
synchronized history  background.js:1399:7
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 11 of the JSON data[Learn More]  background.js:648:31
Unchecked lastError value: Error: win is null  ExtensionCommon.jsm:304
```

**Comment by OlegYch** [comment]
works with 'new youtube'

**Comment by OlegYch** [comment]
i guess i'll be using 'new youtube' now

**Comment by sniklaus** [comment]
Thank you for sharing the debug information! The `JSON.parse: unexpected non-whitespace` error is probably due to getting data from the old Youtube theme. I am happy to hear that the new Youtube theme works for you, Oleg! My apologies for having removed the support for the old theme but I figured that it is better that I invest all my efforts into supporting the new theme moving forward. Thanks again for sharing the debug information!

**Comment by OlegYch** [comment]
@sniklaus np, thanks for the extension
